name: AI Assistant
on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request_review:
    types: [ submitted ]
jobs:
  assistant:
    # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.22
    uses: sei-protocol/uci/.github/workflows/ai-assistant.yml@4bd0b7826bdf7966c2bd899b8810a3aaaa52e80d
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    secrets: inherit
    with:
      # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.22
      uci-ref: 4bd0b7826bdf7966c2bd899b8810a3aaaa52e80d
      allowed-team: 'sei-protocol/sei-core'
